baseURL = "https://keramik.bangunan.co/"
languageCode = "id"
title = "Keramik Bangunan | Distributor Kermaik Lantai Kermaik Dinding Granit Marmer"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Agen Keramik berkualitas - Jual Keramik Lantai, Keramik Dinding, Granit, dan Marmer dengan harga bersaing dan pengiriman free ongkir."
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jual keramik lantai", "keramik dinding", "granit", "marmer", "keramik murah", "distributor keramik", "keramik rumah", "keramik mozaik", "keramik batu alam"]
  base_price = 35000
  price_range = 50000
  free_shipping = true
  materials = [
  "Keramik Lantai Standar",
  "Keramik Dinding",
  "Granit",
  "Marmer",
  "Keramik Batu Alam",
  "Keramik Mozaik"
  ]
  categories = ["Keramik Lantai", "Keramik Dinding", "Granit", "Marmer", "Keramik Batu Alam", "Keramik Mozaik"]
  payment_methods = ["COD (Cash On Delivery)", "Transfer Bank", "Bayar Ditempat", "Transfer Setelah Terkirim"]
  area_served = [
    "Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Bandung", "Cimahi", "Sukabumi", "Cirebon", "Garut", "Tasikmalaya", "Sumedang", "Subang", "Karawang", "Purwakarta", "Cianjur", "Majalengka", "Indramayu", "Kuningan", "Banjar", "Pangandaran", "Kabupaten Bandung", "Kabupaten Bogor", "Kabupaten Bekasi", "Kabupaten Cirebon", "Kabupaten Garut", "Kabupaten Indramayu", "Kabupaten Karawang", "Kabupaten Kuningan", "Kabupaten Majalengka", "Kabupaten Pangandaran", "Kabupaten Purwakarta", "Kabupaten Subang", "Kabupaten Sukabumi", "Kabupaten Sumedang", "Kabupaten Tasikmalaya", "Serang", "Cilegon", "Tangerang Selatan", "Lebak", "Pandeglang", "Kabupaten Tangerang", "Kabupaten Serang", "Semarang", "Surakarta", "Magelang", "Salatiga", "Pekalongan", "Tegal", "Cilacap", "Purwokerto", "Pati", "Jepara", "Kudus", "Demak", "Blora", "Grobogan", "Kendal", "Temanggung", "Wonosobo", "Purworejo", "Kabupaten Magelang", "Kabupaten Boyolali", "Kabupaten Klaten", "Kabupaten Sragen", "Kabupaten Karanganyar", "Kabupaten Sukoharjo", "Kabupaten Wonogiri", "Kabupaten Pati", "Kabupaten Blora", "Kabupaten Grobogan", "Kabupaten Kudus", "Kabupaten Jepara", "Kabupaten Demak", "Kabupaten Batang", "Kabupaten Pekalongan", "Kabupaten Pemalang", "Kabupaten Tegal", "Kabupaten Brebes", "Kabupaten Cilacap", "Kabupaten Banyumas", "Kabupaten Purbalingga", "Kabupaten Banjarnegara", "Kabupaten Kebumen", "Kabupaten Temanggung", "Kabupaten Wonosobo", "Kabupaten Kendal", "Kabupaten Semarang", "Kabupaten Purworejo", "Surabaya", "Malang", "Batu", "Blitar", "Kediri", "Mojokerto", "Madiun", "Pasuruan", "Probolinggo", "Jember", "Lumajang", "Bondowoso", "Banyuwangi", "Situbondo", "Ngawi", "Magetan", "Pacitan", "Ponorogo", "Trenggalek", "Tulungagung", "Kabupaten Sidoarjo", "Kabupaten Gresik", "Kabupaten Lamongan", "Kabupaten Bojonegoro", "Kabupaten Tuban", "Kabupaten Jombang", "Kabupaten Nganjuk", "Kabupaten Madiun", "Kabupaten Magetan", "Kabupaten Ngawi", "Kabupaten Pacitan", "Kabupaten Ponorogo", "Kabupaten Blitar", "Kabupaten Tulungagung", "Kabupaten Kediri", "Kabupaten Malang", "Kabupaten Probolinggo", "Kabupaten Pasuruan", "Kabupaten Lumajang", "Kabupaten Jember", "Kabupaten Bondowoso", "Kabupaten Banyuwangi", "Kabupaten Situbondo"
  ]
  return_policies = [
  "Barang bisa ditukar dalam 1 hari jika tidak sesuai.",
  "Penggantian atau pengembalian gratis untuk barang dengan cacat produksi.",
  "Barang yang tidak sesuai pesanan dapat dikembalikan tanpa biaya tambahan."
  ]

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Agen Keramik Berkualitas"
  hero_description = "Kami menawarkan berbagai jenis keramik berkualitas seperti keramik lantai, keramik dinding, granit, dan marmer. Tersedia dalam berbagai ukuran dan motif. Solusi ideal untuk lantai dan dinding rumah Anda."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog Keramik"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan keramik berkualitas tinggi dengan berbagai pilihan warna dan motif, harga pabrik, dan layanan pengiriman free ongkir. Juga, konsultasi gratis untuk membantu Anda memilih keramik yang tepat untuk proyek Anda."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "keramik.bangunan.co menawarkan berbagai jenis keramik berkualitas seperti keramik lantai, keramik dinding, granit, dan marmer. Kami mengutamakan kepuasan pelanggan dengan produk SNI dan harga yang langsung pabrik. Pilih kami sebagai mitra terbaik penyedia kermik untuk rumah atau bangunan Anda."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Andi|Joko|Eko|Deni|Rudi|Hendra|Agus|Wawan|Rio}"
  message = "{Saya membeli keramik lantai dari keramik.bangunan.co untuk {proyek|pekerjaan} rumah saya, dan hasilnya {sangat memuaskan|luar biasa|memuaskan}. {Kualitas produk|Mutu barang} {sangat baik|unggul|tinggi} dan {harga yang murah|harga terjangkau|biaya yang bersahabat}.|Layanan keramik.bangunan.co {sangat membantu|luar biasa|efektif} untuk memilih keramik yang tepat bagi rumah saya. Produk yang saya {beli|pesan} {berkualitas|handal} dan {sesuai|cocok} dengan kebutuhan saya.}"
  response = "{Terima kasih atas kepercayaan Anda! Kami senang dapat menyediakan keramik {berkualitas|unggul|terbaik} untuk {proyek|pekerjaan} rumah Anda.|Kami menghargai kepercayaan Anda. Terima kasih telah memilih kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Dewi|Ayu|Sari|Lina|Fitri|Diah|Nur|Maya}"
  message = "{keramik.bangunan.co {sangat membantu|mempermudah} dalam memilih {keramik|produk keramik} untuk {rumah|hunian} saya. Produk yang saya {beli|pesan} {berkualitas|baik|handal} dan {sesuai|cocok} dengan kebutuhan saya.|Saya {sangat puas|terkesan|senang} dengan layanan keramik.bangunan.co. {Keramik|Produk keramik} yang saya pilih {berkualitas|tahan lama} dan sesuai dengan {ekspektasi|harapan} saya.}"
  response = "{Kami sangat menghargai ulasan Anda. Senang mendengar bahwa Anda puas dengan {keramik|produk} dari kami.|Terima kasih atas ulasannya. Kami senang bisa membantu memenuhi kebutuhan Anda!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Agus|Bayu|Faisal|Galih|Rizal|Bambang|Ali|Fajar|Toni}"
  message = "{Produk keramik dinding dari keramik.bangunan.co memiliki {banyak pilihan|beragam opsi} {warna|variasi warna} dan {ukuran|dimensi} juga {motif|desain}, {cocok|sesuai} untuk {proyek|usaha} perumahan saya. Proses pembelian dan {pengirimannya|pengiriman} {juga cepat|sangat efisien|lancar}.|Saya {sangat puas|terkesan|senang} dengan keramik dinding yang saya {pesan|beli} dari keramik.bangunan.co. {Warna|Variasi warna} dan {ukuran|dimensi} {sangat memuaskan|tepat} untuk proyek rumah saya.}"
  response = "{Terima kasih! Kami berkomitmen untuk menyediakan keramik {berkualitas|unggul} dengan layanan {terbaik|yang prima}.|Kami senang bisa memenuhi kebutuhan Anda! Terima kasih atas kepercayaannya.}"
  rating = 4.6

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Eko|Toni|Hendra|Dedi|Gilang|Ari|Wawan|Gani|Yudi}"
  message = "{Saya {sangat puas|terkesan|senang} dengan {granit|keramik granit} dari keramik.bangunan.co. {Kualitas|Mutu} {produk|barang}nya {sangat baik|unggul|luar biasa} dan {presisi|tepat} untuk {lantai|permukaan} rumah saya.|Kolam terpal dari kolam.bangunan.co {berkualitas|kokoh|tahan lama} dan sesuai dengan {kebutuhan|keperluan} budidaya ikan saya.}"
  response = "{Senang mendengar Anda puas dengan produk kami. Terima kasih atas kepercayaannya!|Kami sangat menghargai kepercayaan Anda. Terima kasih sudah memilih layanan kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Lina|Dewi|Ayu|Sari|Fitri|Maya|Nur|Diah}"
  message = "{Pelayanan keramik.bangunan.co {sangat memuaskan|luar biasa|hebat}. Produk {keramik|keramik lantai} yang saya {beli|pesan} {sangat berkualitas|berkualitas tinggi|handal} dan {sesuai|cocok} dengan {harapan|ekspektasi|keinginan} saya.|Saya {senang|terkesan|puas} dengan layanan dari keramik.bangunan.co. Keramik yang saya pilih {berkualitas|kokoh|tahan lama} dan sesuai dengan kebutuhan saya.}"
  response = "{Terima kasih! Kami senang dapat {membantu|melayani} Anda dengan keramik {terbaik|unggul}.|Kami sangat menghargai ulasan Anda. Terima kasih telah mempercayakan proyek Anda kepada kami!}"
  rating = 4.5

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Deni|Rizal|Rio|Benny|Yanto|Galih|Toni|Faisal|Wawan}"
  message = "{Keramik lantai dari keramik.bangunan.co {sangat sesuai|tepat|cocok} dengan kebutuhan {proyek|usaha} renovasi rumah saya. Proses {pengirimannya|pengiriman} {cepat|aman|efisien} dan {terjamin|lancar|rapi}.|Saya {puas|terkesan|senang} dengan keramik lantai dari keramik.bangunan.co. Layanan pengirimannya {profesional|cepat|efisien} dan sesuai dengan kebutuhan proyek saya.}"
  response = "{Kami {senang|gembira} mendengar bahwa Anda puas dengan produk kami. Terima kasih atas {ulasannya|kepercayaannya}!|Terima kasih telah mempercayakan proyek Anda kepada kami. Kami senang Anda puas dengan hasilnya.}"
  rating = 4

[[params.tabelItems]]
  name = "Keramik Lantai Standar"
  price = "35.000 - 120.000 /m"
[[params.tabelItems]]
  name = "Keramik Marmer"
  price = "250.000 - 2.000.000 /m"
[[params.tabelItems]]
  name = "Keramik Granit"
  price = "120.000 - 280.000 /m"
[[params.tabelItems]]
  name = "Keramik Batu Alam"
  price = "360.000 - 450.000 /m"
[[params.tabelItems]]
  name = "Keramik Mozaik"
  price = "20.000 - 120.000 /m"
[[params.tabelItems]]
  name = "Keramik Tembok"
  price = "90.000 - 500.000 /m"

[params.appliList]
  "Keramik Lantai Standar" = "interior rumah, ruang tamu, kamar tidur"
  "Keramik Dinding" = "dinding kamar mandi, dinding dapur"
  "Keramik Granit" = "lantai ruang utama, aula, ruang kantor"
  "Keramik Marmer" = "ruang tamu mewah, lobby, hotel"
  "Keramik Batu Alam" = "teras, taman, area luar rumah"
  "Keramik Mozaik" = "kolam renang, kamar mandi, dinding dekoratif"

[params.kegunaanList]
  "Keramik Lantai Standar" = "cocok untuk lantai rumah atau ruang tamu dengan desain sederhana"
  "Keramik Dinding" = "digunakan untuk memperindah dinding kamar mandi atau dapur"
  "Keramik Granit" = "dirancang untuk lantai ruang besar dengan kesan mewah dan elegan"
  "Keramik Marmer" = "cocok untuk ruang tamu mewah, lobby hotel, atau bangunan komersial"
  "Keramik Batu Alam" = "cocok untuk area outdoor seperti teras atau taman dengan kesan natural"
  "Keramik Mozaik" = "digunakan untuk kolam renang, kamar mandi, atau dinding dengan elemen dekoratif"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
  title = "Agen Keramik Lantai, Dinding, Granit & Marmer | "
  highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"